package me.adpuckey.plugins.aprilonirc.irc;

public enum MessageTypes { CHANMSG, QUERYMSG, CHAN_ACTION, QUERY_ACTION, QUIT, JOIN, PART, MODE, KICK, BAN, PING,
NICK, WHOIS, TOPIC, TOPIC_SET_BY, TOPIC_CHANGE, NUMERIC_CODE, UNKNOWN, WHOIS_END, AUTH, NOTICE, MOTD, END_MOTD,
SELFMODE }